name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'
      - 'issue-*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release|issue-[0-9]+)$ ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run build (if applicable)
        run: npm run build --if-present

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          CI: true
